# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            VisionEval
tagline:          'A Jekyll theme'
description:      'A common framework for strategic planning models.'
url:              http://visioneval.org
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'VisionEval'
  url:            https://github.com/visioneval

paginate:         5

# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

whitelist: [jekyll-analytics]

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-111927800-1      # From Google Analytics
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Custom vars
# version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

github: 
  repo: https://github.com/visioneval/visioneval

  
repository: visioneval/visioneval
